strategies:
  long_only_topk:
    k: 5
    min_score: null
    max_positions: 5
    position_sizing: equal
    stop_loss: 0.08
    take_profit: 0.20

  long_short_neutral:
    long_k: 5
    short_k: 5
    net_exposure: 0.0
    stop_loss: 0.10

  regime_filtered:
    k: 5
    regimes: ["high_volatility", "near_52w_low"]

simulation:
  initial_capital: 100000
  slippage_bps: 5
  commission_per_trade: 0.0
  rebalance: "daily"
  allow_reinvestment: true
  exact_mode: true

benchmarks:
  tickers: ["SPY"]
