name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]   # keep this stable; upgrade later if needed

    env:
      PYTHONPATH: ${{ github.workspace }}
      MPLBACKEND: Agg             # avoid GUI issues in matplotlib

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Ensure parquet works even if not pinned in requirements
          python - <<'PY'
import importlib, sys
try:
    importlib.import_module("pyarrow")
except Exception:
    print("Installing pyarrow (not found in requirements)...")
    import subprocess; subprocess.check_call([sys.executable, "-m", "pip", "install", "pyarrow"])
PY
          pip install pytest

      - name: Run tests
        run: pytest -q
